### ISSUE TITLE
Key access..

### ISSUE THREAD

**Issue by AmokraneIlhem** [natml-hub/YOLOX#1]
Hi, thanks for this great work!
Please how to get the key of NatML to be able to execute and run this project?
Thanks in advance.

**Comment by olokobayusuf** [comment]
Hey @AmokraneIlhem , sorry for the late response on this! You can grab an access key from [your account page](https://hub.natml.ai/account/developers) on NatML Hub. Let me know if you have any further questions, and make sure to join our community [on Discord](https://natml.ai/community).
